import './globals.css'

export const metadata = {
  title: 'Photo tagging app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-primary'>{children}</body>
    </html>
  )
}
